// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "7d53ff6cde081b9ca005f94090d2f45ab7feeaae8894b24db29bd4635dae2c36")
